### ISSUE TITLE
slackr_upload (possibly other functions) failing in large workspaces

### ISSUE THREAD

**Issue by dankearney** [mrkaye97/slackr#148]
I work at a larger corporation (several thousand Slack users) and had some trouble getting a bot working in our production Slack environment after running in our dev environment. I used httr::verbose and saw that in production, with the larger production workspace, it was making dozens of calls to api.list, even when the channels variable was explicitly provided. Looking at the code, for large workspaces, slackr_chtrans() is a heavy operation, eventually failing as it gets rate-limited. I removed slackr_chtrans() and tweaked the code to not validate the channel as a workaround. I would recommend avoiding slackr_chtrans() and validating the channels variable with a regex when it's explicitly provided in the args.

**Comment by mrkaye97** [comment]
Hey Dan,

Thanks for the suggestion. What version are you on? AFAIK, this problem arises because there's no great way to get all of the channels in a large workspace without looping. 

I like the idea to allow an explicit channel ID to be passed into `slackr_***()` instead of a channel name, and that should be a pretty easy thing to allow for in the package. Is that what you're thinking? Then you'd be able to avoid calling the API in from `slackr_chtrans()` altogether.

**Comment by dankearney** [comment]
Thanks for responding! Big fan of this library, by the way! Right now my code is just using this function, modified to avoid `slackr_chtrans()`: https://github.com/mrkaye97/slackr/blob/master/R/slackr_upload.R 

My version takes in an explicit channel string and passes it into the body of the POST request without validating against `slackr_chtrans()`. The API accepts it. Channel ID would work too but I suppose the channel string is more convenient.

**Comment by mrkaye97** [comment]
Oh wow, as in you don't need to translate the channels at all? I'll run some tests on this tonight, but that'd be awesome. I'll report back later. Thanks again!

**Comment by mrkaye97** [comment]
Should be fixed in #149 !
