### ISSUE TITLE
Wondering about using slackr environment variables with Github Actions

### ISSUE THREAD

**Issue by invisibae** [mrkaye97/slackr#175]
Hi!

I am trying to automate my slackr posts through Github Actions and I have a question:

Was trying to run an [R script that included slackr](https://github.com/invisibae/slack_bot/blob/main/some_tests.R) through a [github aciton](https://github.com/invisibae/slack_bot/runs/6256910652?check_suite_focus=true) and I keep running into a problem where my script runs without any errors but fails to post to slack because while the requisite environment variables ('SLACK_CHANNEL', 'SLACK_TOKEN', 'SLACK_USERNAME', etc.) are present in the action environment, they're all unfortunately blank.

It was my understanding that I could set up environment variables ahead of time through [Actions Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets), call the env and specify the variables [in my yaml script](https://github.com/invisibae/slack_bot/actions/runs/2257803851/workflow), and simply use slackr() along with Sys.getenv() to point the script to my env variables rather than using slackr_setup and exposing my API key.  

While I'm encouraged by the fact that R seems to be seeing the env variables I set up through Action secrets, I am still unsure about why R thinks they are blank.  Could it be that I am declaring the environment at the wrong point in the yaml file?  Is R simply incompatible with Actions Secrets?  Something else? 

<img width="513" alt="Screen Shot 2022-05-02 at 8 22 49 AM" src="https://user-images.githubusercontent.com/68254592/166232851-0e195952-821b-49e2-9861-c4e91f2d6bc7.png">

**Comment by mrkaye97** [comment]
Hey, thanks for putting in the issue. FYI, this isn't actually a `slackr` issue -- AFAICT you jut have your CI config or the secrets set up incorrectly. You can see [how we did it for `slackr](https://github.com/mrkaye97/slackr/blob/master/.github/workflows/R-CMD-check.yaml#L35-L44). It's tough for me to tell what the actual problem is, but my suspicion is that the secrets are defined as blank strings. In our CI runs, you can see env vars printed like this: https://github.com/mrkaye97/slackr/runs/5612881932?check_suite_focus=true#step:9:8

**Comment by invisibae** [comment]
Any advice on what might've gone wrong in CI config?  I went back and double checked my environment secrets to make sure they weren't blank and I'm kind of at a loss.  My next move will probably be to try to work backwards from your template, but I'm just trying to figure out where I went wrong here.

**Comment by invisibae** [comment]
NVM!
