### ISSUE TITLE
Not able to post images to a Slack group, only text!

### ISSUE THREAD

**Issue by pabmiranda** [mrkaye97/slackr#199]
Hey, I need some help.

I have an app that is already installed in Slack + I've also done the slackr_setup successfully. The truth is that I can only send messages to the Slack group I added the app (bot) using the slackr_bot function. The bot has the file:write scop included.

However, I can't add images (ggplots) to the slack group using hte bot. When I use the slackr_bot function, I only got the name of the image printed in the UI of Slack. When I use all of the other functions, such as slackr_dev or ggslackr I get the message: **The slack API returned an error: channel_not_found** 

Can you guys please shed some light on this issue? [feel free to ask for more information]

**Comment by mrkaye97** [comment]
I might check this out: https://api.slack.com/messaging/webhooks

I think it's pretty likely this is a limitation of Slack webhooks. It might be that they can only send text / blocks. Can you try generating a user token instead of a bot token and seeing if you get the same issues? Or is that outside of what's allowed by your workspace?
