### ISSUE TITLE
files.upload method is deprecated. Upcoming breakage of `slackr::file_upload()`

### ISSUE THREAD

**Issue by davidski** [mrkaye97/slackr#200]
The Slack [files.upload method](https://api.slack.com/methods/files.upload) is being deprecated. New applications created after May 8th will not be able to use it and pre-existing apps will loose access in March of 2025. There are new methods to replace it [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal).

We'll need to retool to continue to have file attachment functionality. Opening a tracking issue here for anyone (myself included) that may have time to work up a PR.

**Comment by mrkaye97** [comment]
Thanks for putting this in! I'll look into it in the next couple weeks. I suspect it'll be a pretty straightforward change, but I also haven't touched the tests or anything in a year or two (and my engineering skills are better now than they were then :P), so there are probably other flaky breakages. 

Feel free to put in a PR for this if you want. I'd like to bundle in a test change that adds mocks to all the API calls instead of calling the real APIs from CI as well.

**Comment by orioles-analytics** [comment]
Hey Matt, think you can help an old friend by doing this? Thanks!

**Comment by mrkaye97** [comment]
> Hey Matt, think you can help an old friend by doing this? Thanks!

@orioles-analytics whoever you are, I'll try to do it this week or next 😄

**Comment by orioles-analytics** [comment]
😁 thank you!

**Comment by mrkaye97** [comment]
just put in #202 to hopefully fix this - you should be able to install from GH. let me know if anyone runs into any issues! I'll try to push a release to CRAN at some point. Going to close this for now, feel free to reopen

**Comment by edgarcutar** [comment]
I'm still getting a `Warning: The slack API returned an error: method_deprecated ` even when using 3.4.0

Is this something on my side?
