### ISSUE TITLE
converting internals to work with json inputs

### ISSUE THREAD

**Issue by yonicd** [mrkaye97/slackr#79]
I came across this [post](https://stackoverflow.com/questions/31905260/sending-json-to-slack-in-a-http-post-request) in SO. It shows how to pass POST requests as [jsons](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22I%20am%20a%20test%20message%20http%3A%2F%2Fslack.com%22%2C%22attachments%22%3A%5B%7B%22text%22%3A%22And%20here%E2%80%99s%20an%20attachment!%22%7D%5D%7D) with bearer. Would it be worth migrating?

**Comment by ajzz** [comment]
This work and JSON is much cleaner. I'm working on migrations on my fork. Will send PRs on things that don't break with current system.

Notes:
1.  Biggest issues seem around channel translation, listing users etc which are invoked by all .
2. I'd also suggest a strategic move away in all documentation to move away from personal tokens to Workspace "app" tokens so scopes can be established before querying instead of catching errors post-query from the response headers.
